### PR TITLE
Adopt to standard license file

### LINKED ISSUE #7: adopt standard license file
Adopt a standard and GitHub-detectable license file.

https://help.github.com/articles/licensing-a-repository/#detecting-a-license

The file should be /LICENSE and not /LICENSE.md.

The current license type (MIT) will be retained.

### PR DESCRIPTION
**Pull request by hanzei**
Fixes #7

### CODE REVIEW

**Comment by philtay** [comment]
We should not change the original copyright line. Just add a new one below:

```
Copyright (c) 2014 Stretchr, Inc.
Copyright (c) 2017 objx contributors
```

**Comment by hanzei** [comment]
Changes made

**Comment by philtay** [comment]
Unfortunately we can't write ```Copyright (c) 2017-present```. Copyright doesn't work like that :-( ```Copyright (c) 2017``` is ok now. ```Copyright (c) 2017 - 2018``` will be ok starting from Jan 1st. The license must be updated every year.

**Comment by hanzei** [comment]
It should be fine now :smile:

**Pull request merged**
